# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'impsum.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImportSummaryDialog(object):
    def setupUi(self, ImportSummaryDialog):
        ImportSummaryDialog.setObjectName("ImportSummaryDialog")
        self.verticalLayout = QtWidgets.QVBoxLayout(ImportSummaryDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblImported = QtWidgets.QLabel(ImportSummaryDialog)
        self.lblImported.setObjectName("lblImported")
        self.verticalLayout.addWidget(self.lblImported)
        self.lblUpdated = QtWidgets.QLabel(ImportSummaryDialog)
        self.lblUpdated.setObjectName("lblUpdated")
        self.verticalLayout.addWidget(self.lblUpdated)
        self.lblErrors = QtWidgets.QLabel(ImportSummaryDialog)
        self.lblErrors.setObjectName("lblErrors")
        self.verticalLayout.addWidget(self.lblErrors)
        self.txtErrors = QtWidgets.QPlainTextEdit(ImportSummaryDialog)
        self.txtErrors.setReadOnly(True)
        self.txtErrors.setMaximumHeight(200)
        self.txtErrors.setObjectName("txtErrors")
        self.verticalLayout.addWidget(self.txtErrors)
        self.buttonBox = QtWidgets.QDialogButtonBox(ImportSummaryDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ImportSummaryDialog)
        QtCore.QMetaObject.connectSlotsByName(ImportSummaryDialog)

    def retranslateUi(self, ImportSummaryDialog):
        _translate = QtCore.QCoreApplication.translate
        ImportSummaryDialog.setWindowTitle(_translate("ImportSummaryDialog", "Import summary"))
        self.lblImported.setText(_translate("ImportSummaryDialog", "Imported:"))
        self.lblUpdated.setText(_translate("ImportSummaryDialog", "Updated:"))
        self.lblErrors.setText(_translate("ImportSummaryDialog", "Errors:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ImportSummaryDialog = QtWidgets.QDialog()
    ui = Ui_ImportSummaryDialog()
    ui.setupUi(ImportSummaryDialog)
    ImportSummaryDialog.show()
    sys.exit(app.exec_())
