# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lookup.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LookupWindow(object):
    def setupUi(self, LookupWindow):
        LookupWindow.setObjectName("LookupWindow")
        LookupWindow.resize(721, 386)
        self.verticalLayout = QtWidgets.QVBoxLayout(LookupWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.infoLabel = QtWidgets.QLabel(LookupWindow)
        self.infoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.infoLabel.setObjectName("infoLabel")
        self.verticalLayout.addWidget(self.infoLabel)
        self.tblSked = QtWidgets.QTableWidget(LookupWindow)
        self.tblSked.setAlternatingRowColors(True)
        self.tblSked.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblSked.setObjectName("tblSked")
        self.tblSked.setColumnCount(7)
        self.tblSked.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblSked.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblSked.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblSked.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblSked.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblSked.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblSked.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblSked.setHorizontalHeaderItem(6, item)
        self.verticalLayout.addWidget(self.tblSked)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem)
        self.refreshButton = QtWidgets.QPushButton(LookupWindow)
        self.refreshButton.setObjectName("refreshButton")
        self.buttonLayout.addWidget(self.refreshButton)
        self.closeButton = QtWidgets.QPushButton(LookupWindow)
        self.closeButton.setObjectName("closeButton")
        self.buttonLayout.addWidget(self.closeButton)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(LookupWindow)
        self.closeButton.clicked.connect(LookupWindow.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LookupWindow)

    def retranslateUi(self, LookupWindow):
        _translate = QtCore.QCoreApplication.translate
        LookupWindow.setWindowTitle(_translate("LookupWindow", "Compatible trasmissions"))
        self.infoLabel.setText(_translate("LookupWindow", "Frequency: 0.0 kHz (±5 kHz) - Found 0 transmissions"))
        self.tblSked.setSortingEnabled(True)
        item = self.tblSked.horizontalHeaderItem(0)
        item.setText(_translate("LookupWindow", "Frequency (kHz)"))
        item = self.tblSked.horizontalHeaderItem(1)
        item.setText(_translate("LookupWindow", "Station"))
        item = self.tblSked.horizontalHeaderItem(2)
        item.setText(_translate("LookupWindow", "Country"))
        item = self.tblSked.horizontalHeaderItem(3)
        item.setText(_translate("LookupWindow", "Language"))
        item = self.tblSked.horizontalHeaderItem(4)
        item.setText(_translate("LookupWindow", "Time"))
        item = self.tblSked.horizontalHeaderItem(5)
        item.setText(_translate("LookupWindow", "Days"))
        item = self.tblSked.horizontalHeaderItem(6)
        item.setText(_translate("LookupWindow", "Actions"))
        self.refreshButton.setText(_translate("LookupWindow", "Refresh"))
        self.closeButton.setText(_translate("LookupWindow", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LookupWindow = QtWidgets.QDialog()
    ui = Ui_LookupWindow()
    ui.setupUi(LookupWindow)
    LookupWindow.show()
    sys.exit(app.exec_())
